---
- name: Patch and Reboot Servers
  hosts: all
  become: yes
  tasks:
    - name: Update all packages (Red Hat-based systems)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update all packages (Debian-based systems)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Reboot the server
      reboot:
        reboot_timeout: 300

